specVersion: 0.0.1
description: >-
  A simple SubQuery project that will return the creation block and timestamp of
  a specified address
repository: ''
schema: ./schema.graphql
network:
  endpoint: wss://polkadot.api.onfinality.io/public-ws
  dictionary: https://api.subquery.network/sq/subquery/dictionary-polkadot
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: system
            method: NewAccount
